# ports.py
from typing import Protocol, Iterable, List
from core.schema import WarningDTO

class Importer(Protocol):
    def load(self, source: str) -> List[WarningDTO]: ...

class Repository(Protocol):
    def clear(self) -> None: ...
    def add_many(self, items: Iterable[WarningDTO]) -> None: ...
    def list_all(self) -> List[WarningDTO]: ...

class CodeProvider(Protocol):
    def get_context(self, file_path: str, start_line: int, window: int = 30) -> str: ...